#define TRUE 1
#define FALSE 0

typedef enum {
    UT_MM_BASE,

    UT_MM_CMPESTRS = UT_MM_BASE,
    UT_MM_CMPESTRZ,
    UT_MM_CMPISTRS,
    UT_MM_CMPISTRZ,
    UT_MM_CMP_EPI16_MASK,
    UT_MM_MASK_CMP_EPI16_MASK,
    UT_MM256_CMP_EPI16_MASK,
    UT_MM256_MASK_CMP_EPI16_MASK,
    UT_MM512_CMP_EPI16_MASK,
    UT_MM512_MASK_CMP_EPI16_MASK,
    UT_MM_CMP_EPI32_MASK,
    UT_MM_MASK_CMP_EPI32_MASK,
    UT_MM256_CMP_EPI32_MASK,
    UT_MM256_MASK_CMP_EPI32_MASK,
    UT_MM512_CMP_EPI32_MASK,
    UT_MM512_MASK_CMP_EPI32_MASK,
    UT_MM_CMP_EPI64_MASK,

    UT_MM_MASK_CMP_EPI64_MASK,
    UT_MM256_CMP_EPI64_MASK,
    UT_MM256_MASK_CMP_EPI64_MASK,
    UT_MM512_CMP_EPI64_MASK,
    UT_MM_CMP_EPU8_MASK,
    UT_MM_MASK_CMP_EPU8_MASK,
    UT_MM256_CMP_EPU8_MASK,
    UT_MM256_MASK_CMP_EPU8_MASK,
    UT_MM512_CMP_EPU8_MASK,
    UT_MM512_MASK_CMP_EPU8_MASK,
    UT_MM_CMP_PD,
    UT_MM256_CMP_PD,
    UT_MM_CMP_PD_MASK,
    UT_MM_MASK_CMP_PD_MASK,
    UT_MM256_CMP_PD_MASK,
    UT_MM256_MASK_CMP_PD_MASK,
    UT_MM512_CMP_PD_MASK,

    UT_MM512_MASK_CMP_PD_MASK,
    UT_MM_CMP_PS,
    UT_MM256_CMP_PS,
    UT_MM_CMP_PS_MASK,
    UT_MM_MASK_CMP_PS_MASK,
    UT_MM256_CMP_PS_MASK,
    UT_MM256_MASK_CMP_PS_MASK,
    UT_MM512_CMP_PS_MASK,
    UT_MM512_MASK_CMP_PS_MASK,

    UT_MM_MAX_COUNT
} InstructionTest;

void RunTest(InstructionTest test);
void init_data();

